### ISSUE TITLE
Split functions into smaller ones

### ISSUE THREAD

**Issue by gnoblet** [gnoblet/hespeR#3]

**Comment by BacotRaphael** [comment]
Done and split into following sub-scripts:
add_hesper_cat.R [compute add group composite indicators]
add_hesper_main.R [compute add main composite columns]
add_top_three.R [used in hesper main, to get top three from top first, second and third prio]
add_val_in_set_binaries.R [to add binaries hesper prevalence, hesper prevalence with subset, hesper undefined in add hesper]
analyse_all.R [messy function to aggregate, to be improved]
analyse_sm.R [messy function to aggregate sm, to be improved]
clean_priorities_subset.R [function just to clean child binaries according to subset, to clean top 1 2 3 binary columns => turns out to be necessary as for Select one there are no child columns by default in dataset, could be reintegrated into add_hesper.R]
drop_undefined.R [self-explanatory]
expand_bin.R [faster version of the two below, kept for add_hesper]
expand_select_multiple.R [older version of the above, expand child binaries from sm]
expand_select_one.R [older version of the above, expand child binaries from so]
is_not_empty.R [helper function not exported to check if fn arguments are not empty NA or NULL at once]
plot_hesper.R [old plot, a mess to clean]
replace_na_subset.R [function to clean binary child columns according to subset, used in add_hesper + clean_top_three]
